# Generated by Django 5.1.1 on 2024-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
