# Generated by Django 5.1.1 on 2024-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_users_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='BUDGET_DESCRIPTION',
            field=models.CharField(default='null', max_length=400),
        ),
    ]
