# Generated by Django 5.1.1 on 2024-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_budget_budget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tracking',
            name='QUANTITY',
            field=models.CharField(max_length=20),
        ),
    ]
