# Generated by Django 4.2.14 on 2024-09-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_income_tracking_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CARBON_CALC',
        ),
    ]
